services:

  app:
    extends:
      file: ktor-base.yml
      service: ktor-base
    depends_on:
      cassandra:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      cassandra-init:
        condition: service_completed_successfully

  envoy:
    extends:
      file: envoy-base.yml
      service: envoy-base
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    extends:
      file: keycloak-base.yml
      service: keycloak-base

  cassandra:
    extends:
      file: cassandra-base.yml
      service: cassandra-base

  cassandra-init:
    extends:
      file: cassandra-init.yml
      service: cassandra-init-base
    depends_on:
      cassandra:
        condition: service_healthy

  liquibase:
    extends:
      file: liquibase-base.yml
      service: liquibase-base
    depends_on:
      cassandra-init:
        condition: service_completed_successfully