services:
  liquibase-base:
    image: "vocabulary-migration-cs:0.0.1"
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:cassandra://cassandra:9042/vocabulary?ssl=false&compliancemode=Liquibase&localdatacenter=dc1
      LIQUIBASE_COMMAND_USERNAME: cassandra
      LIQUIBASE_COMMAND_PASSWORD: cassandra
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: vocabulary
